wandb_version: 1

model_type:
  desc: null
  value: Baseline-CLS
num_train_epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0001
train_batch_size:
  desc: null
  value: 16
eval_batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.8.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698722947.344062
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.15.5
      6: 4.8.0
      8:
      - 5
